[workspace]
resolver = "3"
members = ["commands/*", "crates/*", "plugins/*", "system"]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
omega = { version = "0.4.0", package = "omega-rs" }
omega-document = "0.4.0"
omega-omarchy = "0.4.0"
omega-preview = "0.4.0"
omega-proto = "0.4.0"

[profile.release]
strip = true
lto = "thin"
