[package]
name = "ai-usage"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
ai-usage-commands = { path = "../../commands/ai-usage" }
chrono = "0.4"
desktop-ui = { path = "../../crates/desktop-ui" }
omega.workspace = true

[dev-dependencies]
omega-preview.workspace = true
serde_json = "1"
