[package]
name = "launcher"
version = "0.1.0"
publish.workspace = true

[package.edition]
workspace = true

[dependencies]
audio-commands = { path = "../../commands/audio" }
bluetooth-commands = { path = "../../commands/bluetooth" }
desktop-ui = { path = "../../crates/desktop-ui" }
display-commands = { path = "../../commands/display" }
media-commands = { path = "../../commands/media" }
omega = { workspace = true }
typesafe = { path = "../../crates/typesafe" }

[dev-dependencies]
omega-preview = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
