[package]
name = "launcher"
version = "0.1.0"
publish.workspace = true

[package.edition]
workspace = true

[dependencies]
audio = { path = "../audio" }
bluetooth = { path = "../bluetooth" }
desktop-ui = { path = "../../crates/desktop-ui" }
display = { path = "../display" }
media = { path = "../media" }
omega = { workspace = true }
typesafe = { path = "../../crates/typesafe" }

[dev-dependencies]
omega-preview = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
