[package]
name = "audio"
version = "0.1.0"
publish.workspace = true

[package.edition]
workspace = true

[dependencies]
audio-commands = { path = "../../commands/audio" }
desktop-ui = { path = "../../crates/desktop-ui" }
omega = { workspace = true }

[dev-dependencies]
omega-preview = { workspace = true }
omega-proto = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
