[package]
name = "media"
version = "0.1.0"
publish.workspace = true

[package.edition]
workspace = true

[dependencies]
desktop-ui = { path = "../../crates/desktop-ui" }
media-commands = { path = "../../commands/media" }
omega = { workspace = true }

[dev-dependencies]
omega-preview = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
