//! The image viewer surface: one picture, a thumbnail strip, and navigation.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use omega::{
    Surface, View,
    keyboard::{Chord, Key, Keymap},
    surface::{Events, Lifecycle, Task},
    ui::{
        Bind, Button, Column, EmptyState, Fit, Glyph, Icon, Image, List, Row, Size, Spacer, Text,
        Viewport, ViewportGesture,
    },
};

use crate::cache::Cache;
use crate::catalog::{Catalog, ImageFile};
use crate::derive::{Deriver, Prepared};

/// Width of the thumbnail strip in logical pixels.
const STRIP_WIDTH: u32 = 168;
/// Vertical chrome around the picture: header, caption, controls, padding.
const CHROME_HEIGHT: u32 = 150;
/// A strip row's height, including its padding.
const ROW_HEIGHT: u32 = 60;
/// Most thumbnails generated by one scheduling pass.
const THUMB_BATCH: usize = 8;

/// Presentation settings.
#[derive(Debug, Clone, omega::Config)]
pub struct Settings {
    /// A directory of images or one image file. Empty shows instructions.
    pub path: String,
    /// Directory for generated display and thumbnail images. Empty uses the
    /// XDG cache directory.
    pub cache: String,
    /// Logical width of the presented window; the picture is fitted to this.
    pub width: u32,
    /// Logical height of the presented window; the picture is fitted to this.
    pub height: u32,
    /// Longest thumbnail side in logical pixels, clamped to 16–256.
    pub thumbnail: u32,
    /// Most directory entries to list, clamped to 1–2000.
    pub max_images: u32,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            path: String::new(),
            cache: String::new(),
            width: 1200,
            height: 800,
            thumbnail: 72,
            max_images: 500,
        }
    }
}

/// Display magnification over the fitted size. `1.0` fits the window.
#[derive(Debug, Clone, Copy, PartialEq)]
struct Zoom(f64);

impl Default for Zoom {
    fn default() -> Self {
        Self(1.0)
    }
}

impl Zoom {
    const MIN: f64 = 0.25;
    const MAX: f64 = 8.0;
    const STEP: f64 = 1.25;

    fn scale(self) -> f64 {
        self.0.clamp(Self::MIN, Self::MAX)
    }

    fn percent(self) -> u32 {
        (self.scale() * 100.0).round() as u32
    }

    fn multiply(self, factor: f64) -> Self {
        Self((self.scale() * factor).clamp(Self::MIN, Self::MAX))
    }

    fn step(self, steps: i32) -> Self {
        self.multiply(Self::STEP.powi(steps))
    }
}

/// Instance state: the catalogue, the selection, and generated derivatives.
#[derive(Debug, Default)]
pub struct Model {
    entries: Vec<ImageFile>,
    current: usize,
    prepared: Option<Prepared>,
    prepared_for: Option<usize>,
    /// Present means handled. `None` records a thumbnail that failed to decode.
    thumbnails: BTreeMap<PathBuf, Option<PathBuf>>,
    pending_thumbnails: BTreeSet<PathBuf>,
    cache: Option<Cache>,
    loaded: bool,
    error: String,
    generation: u64,
    next_task: u64,
    /// The transform the surface last observed from the renderer.
    zoom: Zoom,
    offset_x: f64,
    offset_y: f64,
    /// The transform the surface last commanded. The renderer adopts it only
    /// when `view_revision` changes.
    view_revision: u32,
    view_zoom: Zoom,
    view_offset_x: f64,
    view_offset_y: f64,
}

/// Local events and task results.
#[derive(Debug, Clone)]
pub enum Message {
    /// The catalogue finished, or was refused.
    Loaded(Result<Vec<ImageFile>, String>),
    /// A display image and its thumbnail are ready.
    Prepared {
        generation: u64,
        result: Result<Prepared, String>,
    },
    /// One strip thumbnail finished.
    Thumbnail {
        path: PathBuf,
        result: Result<PathBuf, String>,
    },
    /// Open the image whose path is this key.
    Open(String),
    /// Move the selection by this many images, wrapping at the ends.
    Step(i32),
    /// Change magnification by this many steps.
    Zoom(i32),
    /// Apply a pointer gesture over the picture.
    Gesture(ViewportGesture),
    /// Return magnification to fit the window.
    ZoomReset,
    /// Select the first image.
    First,
    /// Select the last image.
    Last,
    /// Re-read the configured path.
    Refresh,
}

/// One picture at a time, with a strip of nearby thumbnails.
///
/// ```sh
/// omega present image-viewer gallery --width 1200 --height 800 \
///   --config '{"path":"/home/me/Pictures"}'
/// ```
#[derive(Debug, omega::Surface)]
#[omega(name = "gallery")]
pub struct Viewer {
    #[omega(config)]
    settings: Settings,
}

impl Viewer {
    fn catalog(&self, model: &mut Model) -> Task<Message> {
        if model.cache.is_none() {
            match self.cache() {
                Ok(cache) => model.cache = Some(cache),
                Err(error) => {
                    model.loaded = true;
                    model.error = error.to_string();
                    return Task::none();
                }
            }
        }
        let path = PathBuf::from(&self.settings.path);
        if path.as_os_str().is_empty() {
            model.loaded = true;
            model.entries.clear();
            model.prepared = None;
            model.thumbnails.clear();
            model.pending_thumbnails.clear();
            model.error.clear();
            return Task::none();
        }
        model.loaded = false;
        let limit = self.settings.max_images.clamp(1, 2000) as usize;
        Task::blocking(
            "catalog",
            move || Catalog::discover(&path, limit),
            |result| Message::Loaded(result.map_err(|error| error.to_string())),
        )
    }

    fn cache(&self) -> omega::Result<Cache> {
        if self.settings.cache.is_empty() {
            Cache::resolve()
        } else {
            Cache::at(&self.settings.cache)
        }
    }

    fn loaded(&self, model: &mut Model, result: Result<Vec<ImageFile>, String>) -> Task<Message> {
        model.loaded = true;
        match result {
            Ok(entries) if entries.is_empty() => {
                model.entries.clear();
                model.prepared = None;
                model.thumbnails.clear();
                model.pending_thumbnails.clear();
                model.error = "No images found under this path".into();
                Task::none()
            }
            Ok(entries) => {
                model.entries = entries;
                model.error.clear();
                model.thumbnails.clear();
                model.pending_thumbnails.clear();
                model.prepared = None;
                model.prepared_for = None;
                let select = self.select(model, 0);
                Task::batch([select, self.schedule_thumbnails(model)])
            }
            Err(error) => {
                model.entries.clear();
                model.prepared = None;
                model.thumbnails.clear();
                model.pending_thumbnails.clear();
                model.error = error;
                Task::none()
            }
        }
    }

    fn prepared(
        &self,
        model: &mut Model,
        generation: u64,
        result: Result<Prepared, String>,
    ) -> Task<Message> {
        if generation != model.generation {
            return Task::none();
        }
        let current = model
            .entries
            .get(model.current)
            .map(|entry| entry.path.clone());
        match result {
            Ok(prepared) => {
                if let Some(path) = current {
                    model
                        .thumbnails
                        .insert(path, Some(prepared.thumbnail.clone()));
                }
                model.prepared_for = Some(model.current);
                model.prepared = Some(prepared);
                model.error.clear();
            }
            Err(error) => {
                if let Some(path) = current {
                    model.thumbnails.insert(path, None);
                }
                model.prepared = None;
                model.prepared_for = None;
                model.error = error;
            }
        }
        self.schedule_thumbnails(model)
    }

    fn thumbnail(
        &self,
        model: &mut Model,
        path: PathBuf,
        result: Result<PathBuf, String>,
    ) -> Task<Message> {
        model.pending_thumbnails.remove(&path);
        model.thumbnails.insert(path, result.ok());
        self.schedule_thumbnails(model)
    }

    /// Select `index`, invalidating any in-flight display render.
    fn select(&self, model: &mut Model, index: usize) -> Task<Message> {
        model.current = index.min(model.entries.len().saturating_sub(1));
        model.generation = model.generation.wrapping_add(1);
        model.prepared = None;
        model.prepared_for = None;
        self.recenter(model);
        self.prepare(model)
    }

    fn prepare(&self, model: &mut Model) -> Task<Message> {
        let (Some(cache), Some(entry)) = (
            model.cache.clone(),
            model.entries.get(model.current).cloned(),
        ) else {
            return Task::none();
        };
        let source = entry.path;
        let generation = model.generation;
        let edge = self.thumbnail_edge();
        Task::blocking(
            "prepare",
            move || Deriver::prepare(&source, &cache, edge),
            move |result| Message::Prepared {
                generation,
                result: result.map_err(|error| error.to_string()),
            },
        )
    }

    /// Generate thumbnails for the visible strip, bounded to one batch.
    fn schedule_thumbnails(&self, model: &mut Model) -> Task<Message> {
        let Some(cache) = model.cache.clone() else {
            return Task::none();
        };
        let edge = self.thumbnail_edge();
        let (first, last) = self.strip_range(model);
        let mut tasks = Vec::new();
        for index in first..last {
            // The current image's thumbnail comes from its prepare task.
            if index == model.current {
                continue;
            }
            let Some(entry) = model.entries.get(index).cloned() else {
                continue;
            };
            if model.thumbnails.contains_key(&entry.path)
                || model.pending_thumbnails.contains(&entry.path)
            {
                continue;
            }
            if tasks.len() >= THUMB_BATCH {
                break;
            }
            model.pending_thumbnails.insert(entry.path.clone());
            let key = format!("thumb-{}", model.next_task);
            model.next_task = model.next_task.wrapping_add(1);
            let work_path = entry.path.clone();
            let done_path = entry.path;
            let cache = cache.clone();
            tasks.push(Task::blocking(
                key,
                move || {
                    Deriver::thumbnail(&work_path, &cache, edge).map(|thumbnail| thumbnail.path)
                },
                move |result| Message::Thumbnail {
                    path: done_path.clone(),
                    result: result.map_err(|error| error.to_string()),
                },
            ));
        }
        Task::batch(tasks)
    }

    fn open_path(&self, model: &mut Model, path: &str) -> Task<Message> {
        let Some(index) = model
            .entries
            .iter()
            .position(|entry| entry.path.as_path() == Path::new(path))
        else {
            return Task::none();
        };
        if index == model.current && model.prepared_for == Some(index) {
            return Task::none();
        }
        let select = self.select(model, index);
        Task::batch([select, self.schedule_thumbnails(model)])
    }

    fn jump(&self, model: &mut Model, index: usize) -> Task<Message> {
        if model.entries.is_empty() {
            return Task::none();
        }
        let select = self.select(model, index);
        Task::batch([select, self.schedule_thumbnails(model)])
    }

    fn step(&self, model: &mut Model, delta: i32) -> Task<Message> {
        if model.entries.is_empty() {
            return Task::none();
        }
        let length = model.entries.len() as i64;
        let next = (model.current as i64 + i64::from(delta)).rem_euclid(length) as usize;
        self.jump(model, next)
    }

    /// The visible strip window, centred on the selection and clamped to bounds.
    fn strip_range(&self, model: &Model) -> (usize, usize) {
        let rows = self.strip_rows();
        let length = model.entries.len();
        let half = rows / 2;
        let start = model
            .current
            .saturating_sub(half)
            .min(length.saturating_sub(rows));
        let end = (start + rows).min(length);
        (start, end)
    }

    fn strip_rows(&self) -> usize {
        (self.display_max().1 / ROW_HEIGHT).clamp(3, 15) as usize
    }

    fn thumbnail_edge(&self) -> u32 {
        self.settings.thumbnail.clamp(16, 256)
    }

    /// Space the picture is fitted into, excluding the strip and chrome.
    fn display_max(&self) -> (u32, u32) {
        (
            self.settings.width.saturating_sub(STRIP_WIDTH + 48).max(1),
            self.settings.height.saturating_sub(CHROME_HEIGHT).max(1),
        )
    }
}

impl Surface for Viewer {
    type Model = Model;
    type Message = Message;
    type Effects = ();

    fn mounted(&self, model: &mut Model, _: &()) -> Task<Message> {
        self.catalog(model)
    }

    fn update(&self, model: &mut Model, message: Message, _: &()) -> Task<Message> {
        match message {
            Message::Loaded(result) => self.loaded(model, result),
            Message::Prepared { generation, result } => self.prepared(model, generation, result),
            Message::Thumbnail { path, result } => self.thumbnail(model, path, result),
            Message::Open(path) => self.open_path(model, &path),
            Message::Step(delta) => self.step(model, delta),
            Message::Gesture(gesture) => {
                self.track(model, gesture);
                Task::none()
            }
            Message::Zoom(steps) => {
                // Keeping the offset fixed keeps the content centre fixed, so a
                // keyboard step is centre-anchored without any size knowledge.
                let target = model.zoom.step(steps);
                let (offset_x, offset_y) = (model.offset_x, model.offset_y);
                self.command(model, target, offset_x, offset_y);
                Task::none()
            }
            Message::ZoomReset => {
                self.command(model, Zoom::default(), 0.0, 0.0);
                Task::none()
            }
            Message::First => self.jump(model, 0),
            Message::Last => self.jump(model, model.entries.len().saturating_sub(1)),
            Message::Refresh => self.catalog(model),
        }
    }

    fn lifecycle(&self, _model: &mut Model, _event: Lifecycle, _: &()) -> Task<Message> {
        Task::none()
    }

    fn render(&self, model: &Model, events: &Events<Message>) -> View {
        let mut root = Column::new()
            .padding(12)
            .gap(10)
            .fill_width()
            .shortcuts(Self::keys(events));

        if !model.loaded {
            return root
                .child(Self::centered(
                    EmptyState::new("Opening…").icon(Glyph::Folder),
                ))
                .into();
        }

        if model.entries.is_empty() {
            let (title, message, icon) = if model.error.is_empty() {
                (
                    "No folder chosen",
                    "Open a folder of images:\n\
                     omega present image-viewer gallery --config '{\"path\":\"~/Pictures\"}'",
                    Glyph::Folder,
                )
            } else {
                ("Nothing to show", model.error.as_str(), Glyph::Warning)
            };
            return root
                .child(EmptyState::new(title).icon(icon).message(message))
                .into();
        }

        root = root
            .child(Self::header(model))
            .child(
                Row::new()
                    .gap(12)
                    .fill_width()
                    .child(Self::strip(self, model, events))
                    .child(Self::stage(self, model, events)),
            )
            .child(Self::controls(model, events));
        root.into()
    }
}

impl Viewer {
    fn header(model: &Model) -> View {
        let current = &model.entries[model.current];
        Row::new()
            .gap(10)
            .fill_width()
            .child(
                Text::new(&current.name)
                    .size(Size::Title)
                    .bold()
                    .fill_width(),
            )
            .child(
                Text::new(format!("{} / {}", model.current + 1, model.entries.len()))
                    .muted()
                    .key("position"),
            )
            .into()
    }

    fn stage(&self, model: &Model, events: &Events<Message>) -> View {
        let mut column = Column::new().gap(8).fill_width();
        match (&model.prepared, model.prepared_for) {
            (Some(prepared), Some(index)) if index == model.current => {
                let area = self.display_max();
                let image = Image::new(prepared.display.to_string_lossy().into_owned())
                    .key("picture")
                    .fit(Fit::None);
                let viewport = Viewport::new()
                    .key("viewport")
                    .fit(Fit::Contain)
                    .zoom(model.view_zoom.scale())
                    .offset(model.view_offset_x, model.view_offset_y)
                    .revision(model.view_revision)
                    .on_wheel(events.on(Message::Gesture))
                    .on_drag(events.on(Message::Gesture))
                    .on_pinch(events.on(Message::Gesture))
                    .fill_width()
                    .height(area.1)
                    .child(image);
                column = column.child(viewport).child(
                    Text::new(Self::caption(prepared))
                        .muted()
                        .size(Size::Caption)
                        .key("details"),
                );
            }
            _ if !model.error.is_empty() => {
                column = column.child(Self::centered(
                    EmptyState::new("Cannot show")
                        .icon(Glyph::Warning)
                        .message(&model.error)
                        .key("picture"),
                ));
            }
            _ => {
                column = column.child(Self::centered(
                    EmptyState::new("Loading…")
                        .icon(Glyph::Camera)
                        .key("picture"),
                ));
            }
        }
        column.into()
    }

    fn strip(&self, model: &Model, events: &Events<Message>) -> View {
        let (first, last) = self.strip_range(model);
        let selected = model
            .entries
            .get(model.current)
            .map(|entry| entry.path.to_string_lossy().into_owned())
            .unwrap_or_default();
        let mut list = List::new()
            .key("strip")
            .width(STRIP_WIDTH)
            .height(self.display_max().1)
            .gap(2)
            .selected(selected)
            .on_select(events.on(Message::Open))
            .on_activate(events.on(Message::Open));

        for index in first..last {
            let entry = &model.entries[index];
            let mut row = Row::new()
                .key(entry.path.to_string_lossy().into_owned())
                .gap(8)
                .padding(4)
                .height(ROW_HEIGHT - 8);
            match model
                .thumbnails
                .get(&entry.path)
                .and_then(|path| path.as_ref())
            {
                Some(path) => {
                    row = row.child(
                        Image::new(path.to_string_lossy().into_owned())
                            .width(64)
                            .height(48),
                    );
                }
                None => row = row.child(Icon::new(Glyph::Camera).size(Size::Title)),
            }
            list = list.child(row.child(Text::new(&entry.name).size(Size::Caption)));
        }

        list.into()
    }

    fn controls(model: &Model, events: &Events<Message>) -> View {
        Row::new()
            .gap(8)
            .fill_width()
            .child(
                Button::new("Previous")
                    .icon(Glyph::Previous)
                    .secondary()
                    .on_press(events.send(Message::Step(-1))),
            )
            .child(
                Button::new("Next")
                    .icon(Glyph::Next)
                    .secondary()
                    .on_press(events.send(Message::Step(1))),
            )
            .child(Spacer::new())
            .child(
                Text::new(format!("{}%", model.zoom.percent()))
                    .muted()
                    .size(Size::Caption)
                    .key("zoom"),
            )
            .child(
                Text::new("←→ navigate · + − zoom · 0 fit · Esc close")
                    .muted()
                    .size(Size::Caption),
            )
            .child(
                Button::new("Refresh")
                    .icon(Glyph::Refresh)
                    .secondary()
                    .on_press(events.send(Message::Refresh)),
            )
            .into()
    }

    fn caption(prepared: &Prepared) -> String {
        let (width, height) = prepared.natural_size;
        if prepared.rotated {
            format!("{width} × {height} · oriented")
        } else {
            format!("{width} × {height}")
        }
    }

    /// Record the transform the renderer reported. The renderer owns the live
    /// gesture, so this only feeds the readout and later commands.
    fn track(&self, model: &mut Model, gesture: ViewportGesture) {
        model.zoom = Zoom(gesture.zoom);
        model.offset_x = gesture.offset_x;
        model.offset_y = gesture.offset_y;
    }

    /// Command a transform. Bumping the revision is what the renderer adopts.
    fn command(&self, model: &mut Model, zoom: Zoom, offset_x: f64, offset_y: f64) {
        model.zoom = zoom;
        model.offset_x = offset_x;
        model.offset_y = offset_y;
        model.view_zoom = zoom;
        model.view_offset_x = offset_x;
        model.view_offset_y = offset_y;
        model.view_revision = model.view_revision.wrapping_add(1);
    }

    /// Center the picture for a newly selected image, keeping the zoom.
    fn recenter(&self, model: &mut Model) {
        let zoom = model.zoom;
        self.command(model, zoom, 0.0, 0.0);
    }

    /// Center one child horizontally in the available width.
    fn centered(child: impl Into<View>) -> View {
        Row::new()
            .fill_width()
            .child(Spacer::new())
            .child(child)
            .child(Spacer::new())
            .into()
    }

    fn keys(events: &Events<Message>) -> Keymap<Bind<()>> {
        let mut keys = Keymap::single(
            Chord::new(Key::ArrowLeft).repeat(),
            events.send(Message::Step(-1)),
        );
        for (chord, message) in [
            (Chord::new(Key::ArrowRight).repeat(), Message::Step(1)),
            (Chord::new(Key::Character('h')).repeat(), Message::Step(-1)),
            (Chord::new(Key::Character('l')).repeat(), Message::Step(1)),
            (Chord::new(Key::Home), Message::First),
            (Chord::new(Key::End), Message::Last),
            (Chord::new(Key::Character('r')), Message::Refresh),
            (Chord::new(Key::Character('+')), Message::Zoom(1)),
            (Chord::new(Key::Character('=')), Message::Zoom(1)),
            (Chord::new(Key::Character('-')), Message::Zoom(-1)),
            (Chord::new(Key::Character('0')), Message::ZoomReset),
        ] {
            keys = keys
                .bind(chord, events.send(message))
                .expect("viewer shortcuts are unique");
        }
        keys
    }
}
