[package]
name = "bluetooth"
version = "0.1.0"
publish.workspace = true

[package.edition]
workspace = true

[dependencies]
bluetooth-commands = { path = "../../commands/bluetooth" }
desktop-ui = { path = "../../crates/desktop-ui" }
omega = { workspace = true }

[dev-dependencies]
omega-preview = { workspace = true }
tokio = { version = "1", features = ["macros", "rt"] }
